### ISSUE TITLE
Bulk retrieval is free?

### ISSUE THREAD

**Issue by s50600822** [awsdocs/amazon-glacier-developer-guide#20]
Correct me if I'm wrong, but in this [doc](https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/restoring-objects-retrieval-options.md?plain=1#L8) we mention bulk retrieval cost the least but we don't say how to calculate. 

<img width="1375" alt="Screenshot 2023-05-08 at 7 00 48 pm" src="https://user-images.githubusercontent.com/5586453/236782887-22a2a208-2613-4441-8126-17985682a879.png">

I did some search and found it's free:
 
<img width="1262" alt="Screenshot 2023-05-08 at 6 58 30 pm" src="https://user-images.githubusercontent.com/5586453/236782738-025d42c1-deb2-4b8e-8f4d-a6cce50e77dd.png">

https://aws.amazon.com/s3/glacier/pricing/
this was also mentioned in https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-glacier-storage-class-amazon-s3-glacier-flexible-retrieval/

If it is true, I think it'd be more user-friendly for the doc to just say so("cost the least" is technically true but ambiguous ).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
